import { Router, Request, Response } from "express";
import { randomUUID } from "crypto";
import { storeCallContext } from "../services/supabaseService";
import { placeCall } from "../services/twilioService";

// Called by the frontend when the user confirms the emergency.
//
// Expected request body:
//   {
//     type: "police" | "fire" | "ems",
//     address: string,
//     situation?: string,   // plain-language context generated by frontend
//     zones?: string[],
//     age?: number
//   }
//
// Response:
//   { success: true, callSid: string }

const router = Router();

router.post("/", async (req: Request, res: Response) => {
  try {
    const { type, address, situation, zones, age } = req.body;

    if (!type || !address) {
      return res.status(400).json({ error: "type and address are required" });
    }

    // 1. Generate a unique ID to link the call context across requests
    const contextId = randomUUID();

    // 2. Store patient context in Supabase — looked up by /api/twiml and /api/respond
    await storeCallContext(contextId, { type, address, situation, zones, age });

    // 3. Build the TwiML URL — Twilio fetches this when the call connects
    const twimlUrl = `${process.env.PUBLIC_URL}/api/twiml?ctx=${contextId}`;

    // 4. Place the outbound call via Twilio
    const callSid = await placeCall(twimlUrl);

    return res.json({ success: true, callSid });
  } catch (err) {
    console.error("Call error:", err);
    return res.status(500).json({ error: "Failed to place call" });
  }
});

export default router;
